/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BottomSheet {
    'arrow': boolean;
    'close': () => Promise<void>;
    'initialPosition': 'top' | 'bottom';
    'open': () => Promise<void>;
  }
  interface BottomSheetIndicator {}
  interface BottomSheetScreen {
    'connectedBottomSheet': HTMLBottomSheetElement;
    'disable': () => Promise<void>;
    'enable': () => Promise<void>;
    'progress': number;
  }
}

declare global {


  interface HTMLBottomSheetElement extends Components.BottomSheet, HTMLStencilElement {}
  var HTMLBottomSheetElement: {
    prototype: HTMLBottomSheetElement;
    new (): HTMLBottomSheetElement;
  };

  interface HTMLBottomSheetIndicatorElement extends Components.BottomSheetIndicator, HTMLStencilElement {}
  var HTMLBottomSheetIndicatorElement: {
    prototype: HTMLBottomSheetIndicatorElement;
    new (): HTMLBottomSheetIndicatorElement;
  };

  interface HTMLBottomSheetScreenElement extends Components.BottomSheetScreen, HTMLStencilElement {}
  var HTMLBottomSheetScreenElement: {
    prototype: HTMLBottomSheetScreenElement;
    new (): HTMLBottomSheetScreenElement;
  };
  interface HTMLElementTagNameMap {
    'bottom-sheet': HTMLBottomSheetElement;
    'bottom-sheet-indicator': HTMLBottomSheetIndicatorElement;
    'bottom-sheet-screen': HTMLBottomSheetScreenElement;
  }
}

declare namespace LocalJSX {
  interface BottomSheet extends JSXBase.HTMLAttributes<HTMLBottomSheetElement> {
    'arrow'?: boolean;
    'initialPosition'?: 'top' | 'bottom';
  }
  interface BottomSheetIndicator extends JSXBase.HTMLAttributes<HTMLBottomSheetIndicatorElement> {}
  interface BottomSheetScreen extends JSXBase.HTMLAttributes<HTMLBottomSheetScreenElement> {
    'connectedBottomSheet'?: HTMLBottomSheetElement;
    'progress'?: number;
  }

  interface IntrinsicElements {
    'bottom-sheet': BottomSheet;
    'bottom-sheet-indicator': BottomSheetIndicator;
    'bottom-sheet-screen': BottomSheetScreen;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


