/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BottomSheetIndicator {}
  interface BottomSheetIndicatorAttributes extends StencilHTMLAttributes {}

  interface BottomSheet {
    'arrow': boolean;
    'initialPosition': 'top' | 'bottom';
  }
  interface BottomSheetAttributes extends StencilHTMLAttributes {
    'arrow'?: boolean;
    'initialPosition'?: 'top' | 'bottom';
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BottomSheetIndicator': Components.BottomSheetIndicator;
    'BottomSheet': Components.BottomSheet;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'bottom-sheet-indicator': Components.BottomSheetIndicatorAttributes;
    'bottom-sheet': Components.BottomSheetAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLBottomSheetIndicatorElement extends Components.BottomSheetIndicator, HTMLStencilElement {}
  var HTMLBottomSheetIndicatorElement: {
    prototype: HTMLBottomSheetIndicatorElement;
    new (): HTMLBottomSheetIndicatorElement;
  };

  interface HTMLBottomSheetElement extends Components.BottomSheet, HTMLStencilElement {}
  var HTMLBottomSheetElement: {
    prototype: HTMLBottomSheetElement;
    new (): HTMLBottomSheetElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'bottom-sheet-indicator': HTMLBottomSheetIndicatorElement
    'bottom-sheet': HTMLBottomSheetElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'bottom-sheet-indicator': HTMLBottomSheetIndicatorElement;
    'bottom-sheet': HTMLBottomSheetElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
